### ISSUE TITLE
Update versions of underlying technologies?

### ISSUE THREAD

**Issue by edeandrea** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs#1]
The catalog app is using Spring Boot 1.5.8 which is from 2017 and considered EOL by the Spring community. Shouldn't we make this more current?

Also the monolith is using the EAP 7.0 images. Shouldn't this be more current as well (EAP 7.2)?

**Comment by danieloh30** [comment]
@edeandrea Monolith app is already deployed on EAP 7.2.2. If you look at the templates in src/main/java/openshift/, those of template don't be used.

For SB version, I will update it soon. Thanks for the suggestions.

**Comment by edeandrea** [comment]
Looks like this was done in #2
