### ISSUE TITLE
[RHPDS-Install]: "fatal: I don't handle protocol '  https'"

### ISSUE THREAD

**Issue by karstengresch** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs#4]
Probably not the right repo to address this issue, but as it appeared when running this lab, I leave it here.

Setup on RHPDS  ("DEV - CCN Roadshow for Dev Track").

When trying to clone this repo via the given URL https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs.git, the error "fatal: I don't handle protocol '  https'" occurs.

```
Looking for git in: git
Using git 2.18.2 from git
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git clone   https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs.git /projects/cloud-native-workshop-v2m1-labs
Cloning into '/projects/cloud-native-workshop-v2m1-labs'...
fatal: I don't handle protocol '  https'
```

Expected behavior: Cloning the repo works.

Workaround: Use git:// instead of https://

**Comment by jamesfalkner** [comment]
Are you using CodeReady workspaces to do this? I just tried it with a cluster provisioned this morning and it works fine, both through the GUI and opening a terminal and doing it there.

I presume you're also using CodeReady Workspaces version 2 (the version bundled with the workshop)?

**Comment by karstengresch** [comment]
Hi @jamesfalkner wow, super fast reply, thanks very much! 

Yes, using CRW, just following the official WS instructions.

Just checked the error message: It comes from git and the normal culprits are special chars in the URL. 

Re-checked the instructions: When using the "click to clipboard" feature, two spaces get inserted in the URL. 

Strangely enough, this doesn't seem related to the source HTML, as it says:

```
<pre class="CodeRay highlight"><code data-lang="none">https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs.git</code></pre>
</div>
```
I.e. no special chars in the text. I therefor assume, it's related to the JavaScript in the documentation, but am not aware where to address this issue.

PS: At least this doesn't seem to be related to agnosticd at all, which is good.

**Comment by danieloh30** [comment]
what is your cluster info and user? Let me take a look at it.

**Comment by karstengresch** [comment]
@danieloh30 - thanks, DM you internally.

**Comment by danieloh30** [comment]
I think your cluster is down and can you try this with Chrome?

**Comment by danieloh30** [comment]
Confirmed. This is Firefox issue and I added notes in the instruction as below:

Step through the prompts, using the following value for **Repository URL**. If you use *FireFox*, press backspace after pasting one-liners:

**Comment by karstengresch** [comment]
Just for documentation: Problem is that the JavaScript for "Click-to-Copy" inserts two special chars. Other workaround therefor is removing the two chars ahead of the URL.

Problem does not occur on Chrome.

**Comment by danieloh30** [comment]
Thanks for the comments.
