### ISSUE TITLE
Git Clone Repository HTTPS fail

### ISSUE THREAD

**Issue by ChrystianDuarte** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs#5]
in the Step through the prompts, using the following value for Repository URL. If you use FireFox, it may end up pasting extra spaces at the end, so just press backspace after pasting:

https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs.git

when try to Add to workspace Fail because Codeready does not support HTTPS

**Comment by ChrystianDuarte** [comment]
we have to use HTTP

http://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-labs.git

and works!!!!

**Comment by danieloh30** [comment]
@ChrystianDuarte That's the firefox bug so you need to try to do via Chrome.
